version: 2
jobs:
 build:
  docker:
   - image: holochain/holonix
  steps:
   - checkout

   - run:
      name: allow unfree nix (for ngrok)
      command: |
       mkdir -p $HOME/.config/nixpkgs
       echo '{ allowUnfree = true; }' >> $HOME/.config/nixpkgs/config.nix

   - run:
      name: start dynamodb
      background: true
      command: nix-shell --run dynamodb

   - run:
      name: wait for dynamodb
      command: nix-shell --run 'aws dynamodb list-tables --endpoint-url=http://localhost:8000'

   - run:
      name: run the tests
      command: nix-shell --run 'cargo test'

workflows:
 version: 2
 build:
  jobs:
   - build
